import {
  calculateRequirementStatus,
  type CategoryCourse,
  type RequirementCategoryDetail,
  type RequirementCategorySummary,
} from '../utils/requirements';

const MOCK_DELAY_MS = 160;

const CATEGORY_IDS = {
  required: 'required',
  requiredElective: 'required_elective',
  specialized: 'specialized',
  liberalArts: 'liberal_arts',
  free: 'free',
} as const;

function delay(ms: number) {
  return new Promise<void>((resolve) => {
    setTimeout(resolve, ms);
  });
}

function createCourse(categoryId: string, course: Omit<CategoryCourse, 'eligibleCategoryIds'> & { eligibleCategoryIds?: string[] }): CategoryCourse {
  return {
    ...course,
    eligibleCategoryIds: course.eligibleCategoryIds ?? (course.matchState === 'not_eligible' ? [] : [categoryId]),
  };
}

function summarizeDetail(detail: RequirementCategoryDetail): RequirementCategorySummary {
  const totalEligibleCourses = detail.courses.filter((course) => course.matchState !== 'not_eligible').length;
  const countedCourses = detail.courses.filter((course) => course.matchState === 'counted_in_this_category').length;
  const plannedCourses = detail.courses.filter((course) => course.takenStatus === 'planned').length;
  const passedCourses = detail.courses.filter((course) => course.takenStatus === 'passed').length;

  return {
    ...detail,
    totalEligibleCourses,
    countedCourses,
    plannedCourses,
    passedCourses,
  };
}

export const mockRequirementCategoryDetails: RequirementCategoryDetail[] = [
  {
    categoryId: CATEGORY_IDS.required,
    categoryName: '必修科目',
    description: '学科で必ず取得する必要がある基礎的な必修科目です。',
    requiredCredits: 24,
    earnedCredits: 20,
    plannedCredits: 2,
    remainingCredits: 2,
    status: calculateRequirementStatus(24, 20, 2),
    courses: [
      createCourse(CATEGORY_IDS.required, {
        courseId: 'basic_math_1',
        courseCode: 'MAT101',
        courseName: '基礎数学I',
        credits: 4,
        yearLevel: 1,
        semester: '前期',
        dayPeriod: '月曜1限',
        instructor: '中村 真',
        takenStatus: 'passed',
        matchState: 'counted_in_this_category',
        countedCategoryId: CATEGORY_IDS.required,
        countedCategoryName: '必修科目',
      }),
      createCourse(CATEGORY_IDS.required, {
        courseId: 'basic_physics_1',
        courseCode: 'PHY101',
        courseName: '基礎物理I',
        credits: 4,
        yearLevel: 1,
        semester: '後期',
        dayPeriod: '火曜2限',
        instructor: '佐藤 亮',
        takenStatus: 'passed',
        matchState: 'counted_in_this_category',
        countedCategoryId: CATEGORY_IDS.required,
        countedCategoryName: '必修科目',
      }),
      createCourse(CATEGORY_IDS.required, {
        courseId: 'programming_basics',
        courseCode: 'INF102',
        courseName: 'プログラミング基礎',
        credits: 4,
        yearLevel: 1,
        semester: '前期',
        dayPeriod: '水曜3限',
        instructor: '鈴木 花',
        takenStatus: 'passed',
        matchState: 'counted_in_this_category',
        countedCategoryId: CATEGORY_IDS.required,
        countedCategoryName: '必修科目',
      }),
      createCourse(CATEGORY_IDS.required, {
        courseId: 'electric_circuits_1',
        courseCode: 'ELEC201',
        courseName: '電気回路基礎',
        credits: 4,
        yearLevel: 2,
        semester: '前期',
        dayPeriod: '木曜2限',
        instructor: '田中 創',
        takenStatus: 'passed',
        matchState: 'counted_in_this_category',
        countedCategoryId: CATEGORY_IDS.required,
        countedCategoryName: '必修科目',
      }),
      createCourse(CATEGORY_IDS.required, {
        courseId: 'laboratory_safety',
        courseCode: 'LAB110',
        courseName: '実験安全設計',
        credits: 4,
        yearLevel: 2,
        semester: '前期',
        dayPeriod: '金曜1限',
        instructor: '小林 守',
        takenStatus: 'passed',
        matchState: 'counted_in_this_category',
        countedCategoryId: CATEGORY_IDS.required,
        countedCategoryName: '必修科目',
      }),
      createCourse(CATEGORY_IDS.required, {
        courseId: 'career_design',
        courseCode: 'CAR210',
        courseName: 'キャリア設計演習',
        credits: 2,
        yearLevel: 2,
        semester: '後期',
        dayPeriod: '月曜4限',
        instructor: '山田 太郎',
        takenStatus: 'planned',
        matchState: 'eligible_for_this_category',
      }),
      createCourse(CATEGORY_IDS.required, {
        courseId: 'signal_intro',
        courseCode: 'SIG214',
        courseName: '信号処理入門',
        credits: 2,
        yearLevel: 2,
        semester: '後期',
        dayPeriod: '火曜3限',
        instructor: '岡本 梓',
        takenStatus: 'not_taken',
        matchState: 'eligible_for_this_category',
      }),
      createCourse(CATEGORY_IDS.required, {
        courseId: 'english_communication',
        courseCode: 'ENG120',
        courseName: '英語コミュニケーション',
        credits: 4,
        yearLevel: 1,
        semester: '前期',
        dayPeriod: '水曜1限',
        instructor: 'M. Brown',
        takenStatus: 'passed',
        matchState: 'counted_in_other_category',
        countedCategoryId: CATEGORY_IDS.liberalArts,
        countedCategoryName: '共通教育',
        eligibleCategoryIds: [CATEGORY_IDS.required, CATEGORY_IDS.liberalArts],
      }),
      createCourse(CATEGORY_IDS.required, {
        courseId: 'research_orientation',
        courseCode: 'RES105',
        courseName: '研究入門セミナー',
        credits: 2,
        yearLevel: 3,
        semester: '前期',
        dayPeriod: '木曜4限',
        instructor: '高橋 直',
        takenStatus: 'not_taken',
        matchState: 'not_eligible',
      }),
    ],
  },
  {
    categoryId: CATEGORY_IDS.requiredElective,
    categoryName: '選択必修',
    description: '条件を満たす複数の授業から必要単位を選んで取得する区分です。',
    requiredCredits: 16,
    earnedCredits: 12,
    plannedCredits: 4,
    remainingCredits: 0,
    status: calculateRequirementStatus(16, 12, 4),
    courses: [
      createCourse(CATEGORY_IDS.requiredElective, {
        courseId: 'embedded_systems',
        courseCode: 'ELEC301',
        courseName: '組込みシステム',
        credits: 4,
        yearLevel: 3,
        semester: '前期',
        dayPeriod: '月曜2限',
        instructor: '渡辺 修',
        takenStatus: 'passed',
        matchState: 'counted_in_this_category',
        countedCategoryId: CATEGORY_IDS.requiredElective,
        countedCategoryName: '選択必修',
      }),
      createCourse(CATEGORY_IDS.requiredElective, {
        courseId: 'measurement_engineering',
        courseCode: 'ELEC302',
        courseName: '計測工学',
        credits: 4,
        yearLevel: 3,
        semester: '後期',
        dayPeriod: '火曜1限',
        instructor: '吉田 仁',
        takenStatus: 'passed',
        matchState: 'counted_in_this_category',
        countedCategoryId: CATEGORY_IDS.requiredElective,
        countedCategoryName: '選択必修',
      }),
      createCourse(CATEGORY_IDS.requiredElective, {
        courseId: 'information_design',
        courseCode: 'ELEC303',
        courseName: '情報設計演習',
        credits: 4,
        yearLevel: 3,
        semester: '前期',
        dayPeriod: '水曜2限',
        instructor: '森 由美',
        takenStatus: 'passed',
        matchState: 'counted_in_this_category',
        countedCategoryId: CATEGORY_IDS.requiredElective,
        countedCategoryName: '選択必修',
      }),
      createCourse(CATEGORY_IDS.requiredElective, {
        courseId: 'advanced_mathematics_seminar',
        courseCode: 'MAT320',
        courseName: '応用数学セミナー',
        credits: 2,
        yearLevel: 3,
        semester: '後期',
        dayPeriod: '木曜2限',
        instructor: '石井 久',
        takenStatus: 'planned',
        matchState: 'eligible_for_this_category',
      }),
      createCourse(CATEGORY_IDS.requiredElective, {
        courseId: 'project_practicum',
        courseCode: 'PRJ330',
        courseName: 'プロジェクト実習',
        credits: 2,
        yearLevel: 4,
        semester: '前期',
        dayPeriod: '金曜3限',
        instructor: '長谷川 透',
        takenStatus: 'planned',
        matchState: 'eligible_for_this_category',
      }),
      createCourse(CATEGORY_IDS.requiredElective, {
        courseId: 'mechanics_fundamentals',
        courseCode: 'MECH201',
        courseName: '機械基礎概論',
        credits: 4,
        yearLevel: 2,
        semester: '前期',
        dayPeriod: '水曜4限',
        instructor: '中島 彩',
        takenStatus: 'passed',
        matchState: 'counted_in_other_category',
        countedCategoryId: CATEGORY_IDS.specialized,
        countedCategoryName: '専門科目',
        eligibleCategoryIds: [CATEGORY_IDS.requiredElective, CATEGORY_IDS.specialized],
      }),
      createCourse(CATEGORY_IDS.requiredElective, {
        courseId: 'research_methods',
        courseCode: 'RES240',
        courseName: '研究手法基礎',
        credits: 2,
        yearLevel: 2,
        semester: '後期',
        dayPeriod: '火曜4限',
        instructor: '小泉 恵',
        takenStatus: 'not_taken',
        matchState: 'eligible_for_this_category',
      }),
      createCourse(CATEGORY_IDS.requiredElective, {
        courseId: 'practice_safety',
        courseCode: 'LAB220',
        courseName: '実習安全特論',
        credits: 2,
        yearLevel: 2,
        semester: '後期',
        dayPeriod: '木曜1限',
        instructor: '清水 望',
        takenStatus: 'not_taken',
        matchState: 'not_eligible',
      }),
    ],
  },
  {
    categoryId: CATEGORY_IDS.specialized,
    categoryName: '専門科目',
    description: '学科の専門性を身につけるための中核科目です。',
    requiredCredits: 18,
    earnedCredits: 18,
    plannedCredits: 0,
    remainingCredits: 0,
    status: calculateRequirementStatus(18, 18, 0),
    courses: [
      createCourse(CATEGORY_IDS.specialized, {
        courseId: 'circuit_theory_1',
        courseCode: 'ELEC201',
        courseName: '回路理論I',
        credits: 4,
        yearLevel: 2,
        semester: '前期',
        dayPeriod: '月曜2限',
        instructor: '山田 太郎',
        takenStatus: 'passed',
        matchState: 'counted_in_this_category',
        countedCategoryId: CATEGORY_IDS.specialized,
        countedCategoryName: '専門科目',
      }),
      createCourse(CATEGORY_IDS.specialized, {
        courseId: 'electromagnetics_1',
        courseCode: 'ELEC202',
        courseName: '電磁気学I',
        credits: 4,
        yearLevel: 2,
        semester: '前期',
        dayPeriod: '火曜2限',
        instructor: '高橋 直',
        takenStatus: 'passed',
        matchState: 'counted_in_this_category',
        countedCategoryId: CATEGORY_IDS.specialized,
        countedCategoryName: '専門科目',
      }),
      createCourse(CATEGORY_IDS.specialized, {
        courseId: 'control_basics',
        courseCode: 'ELEC203',
        courseName: '制御工学基礎',
        credits: 4,
        yearLevel: 3,
        semester: '前期',
        dayPeriod: '水曜3限',
        instructor: '藤井 拓',
        takenStatus: 'passed',
        matchState: 'counted_in_this_category',
        countedCategoryId: CATEGORY_IDS.specialized,
        countedCategoryName: '専門科目',
      }),
      createCourse(CATEGORY_IDS.specialized, {
        courseId: 'signal_processing_lab',
        courseCode: 'ELEC204',
        courseName: '信号処理実験',
        credits: 2,
        yearLevel: 3,
        semester: '後期',
        dayPeriod: '木曜2限',
        instructor: '鈴木 花',
        takenStatus: 'passed',
        matchState: 'counted_in_this_category',
        countedCategoryId: CATEGORY_IDS.specialized,
        countedCategoryName: '専門科目',
      }),
      createCourse(CATEGORY_IDS.specialized, {
        courseId: 'semiconductor_experiment',
        courseCode: 'ELEC205',
        courseName: '半導体実験',
        credits: 2,
        yearLevel: 3,
        semester: '後期',
        dayPeriod: '金曜1限',
        instructor: '小林 守',
        takenStatus: 'passed',
        matchState: 'counted_in_this_category',
        countedCategoryId: CATEGORY_IDS.specialized,
        countedCategoryName: '専門科目',
      }),
      createCourse(CATEGORY_IDS.specialized, {
        courseId: 'robotics_practice',
        courseCode: 'ELEC206',
        courseName: 'ロボティクス実習',
        credits: 2,
        yearLevel: 4,
        semester: '前期',
        dayPeriod: '月曜4限',
        instructor: '田村 仁',
        takenStatus: 'passed',
        matchState: 'counted_in_this_category',
        countedCategoryId: CATEGORY_IDS.specialized,
        countedCategoryName: '専門科目',
      }),
      createCourse(CATEGORY_IDS.specialized, {
        courseId: 'power_systems',
        courseCode: 'ELEC207',
        courseName: '電力システム概論',
        credits: 2,
        yearLevel: 4,
        semester: '後期',
        dayPeriod: '火曜3限',
        instructor: '伊藤 司',
        takenStatus: 'not_taken',
        matchState: 'eligible_for_this_category',
      }),
      createCourse(CATEGORY_IDS.specialized, {
        courseId: 'design_workshop',
        courseCode: 'DES210',
        courseName: '設計ワークショップ',
        credits: 4,
        yearLevel: 3,
        semester: '前期',
        dayPeriod: '木曜3限',
        instructor: '森 由美',
        takenStatus: 'passed',
        matchState: 'counted_in_other_category',
        countedCategoryId: CATEGORY_IDS.requiredElective,
        countedCategoryName: '選択必修',
        eligibleCategoryIds: [CATEGORY_IDS.specialized, CATEGORY_IDS.requiredElective],
      }),
    ],
  },
  {
    categoryId: CATEGORY_IDS.liberalArts,
    categoryName: '共通教育',
    description: '全学的な基礎力や幅広い教養を身につけるための区分です。',
    requiredCredits: 14,
    earnedCredits: 0,
    plannedCredits: 0,
    remainingCredits: 14,
    status: calculateRequirementStatus(14, 0, 0),
    courses: [
      createCourse(CATEGORY_IDS.liberalArts, {
        courseId: 'english_communication_1',
        courseCode: 'ENG101',
        courseName: '英語コミュニケーションI',
        credits: 2,
        yearLevel: 1,
        semester: '前期',
        dayPeriod: '月曜3限',
        instructor: 'M. Brown',
        takenStatus: 'not_taken',
        matchState: 'eligible_for_this_category',
      }),
      createCourse(CATEGORY_IDS.liberalArts, {
        courseId: 'philosophy_basics',
        courseCode: 'GEN110',
        courseName: '哲学入門',
        credits: 2,
        yearLevel: 1,
        semester: '後期',
        dayPeriod: '火曜1限',
        instructor: '井上 希',
        takenStatus: 'not_taken',
        matchState: 'eligible_for_this_category',
      }),
      createCourse(CATEGORY_IDS.liberalArts, {
        courseId: 'sports_science',
        courseCode: 'GEN112',
        courseName: 'スポーツ科学',
        credits: 2,
        yearLevel: 1,
        semester: '前期',
        dayPeriod: '水曜4限',
        instructor: '吉田 仁',
        takenStatus: 'not_taken',
        matchState: 'eligible_for_this_category',
      }),
      createCourse(CATEGORY_IDS.liberalArts, {
        courseId: 'global_culture',
        courseCode: 'GEN115',
        courseName: 'グローバル文化論',
        credits: 2,
        yearLevel: 2,
        semester: '後期',
        dayPeriod: '木曜1限',
        instructor: '佐々木 玲',
        takenStatus: 'not_taken',
        matchState: 'eligible_for_this_category',
      }),
      createCourse(CATEGORY_IDS.liberalArts, {
        courseId: 'career_language',
        courseCode: 'ENG130',
        courseName: 'キャリア英語演習',
        credits: 2,
        yearLevel: 2,
        semester: '前期',
        dayPeriod: '金曜2限',
        instructor: 'M. White',
        takenStatus: 'passed',
        matchState: 'counted_in_other_category',
        countedCategoryId: CATEGORY_IDS.requiredElective,
        countedCategoryName: '選択必修',
        eligibleCategoryIds: [CATEGORY_IDS.liberalArts, CATEGORY_IDS.requiredElective],
      }),
      createCourse(CATEGORY_IDS.liberalArts, {
        courseId: 'information_ethics',
        courseCode: 'GEN120',
        courseName: '情報倫理',
        credits: 2,
        yearLevel: 1,
        semester: '後期',
        dayPeriod: '木曜3限',
        instructor: '高橋 直',
        takenStatus: 'not_taken',
        matchState: 'not_eligible',
      }),
    ],
  },
  {
    categoryId: CATEGORY_IDS.free,
    categoryName: '自由科目',
    description: '卒業要件の自由度が高い科目群です。各学科の方針に応じて扱いが変わります。',
    requiredCredits: 4,
    earnedCredits: 0,
    plannedCredits: 0,
    remainingCredits: 4,
    status: calculateRequirementStatus(4, 0, 0),
    courses: [
      createCourse(CATEGORY_IDS.free, {
        courseId: 'internship_basics',
        courseCode: 'FRE101',
        courseName: 'インターンシップ基礎',
        credits: 2,
        yearLevel: 3,
        semester: '前期',
        dayPeriod: '月曜5限',
        instructor: '長谷川 透',
        takenStatus: 'not_taken',
        matchState: 'eligible_for_this_category',
      }),
      createCourse(CATEGORY_IDS.free, {
        courseId: 'reading_seminar',
        courseCode: 'FRE102',
        courseName: '読書セミナー',
        credits: 2,
        yearLevel: 2,
        semester: '後期',
        dayPeriod: '火曜4限',
        instructor: '清水 望',
        takenStatus: 'not_taken',
        matchState: 'eligible_for_this_category',
      }),
      createCourse(CATEGORY_IDS.free, {
        courseId: 'volunteer_practice',
        courseCode: 'FRE103',
        courseName: '地域ボランティア実践',
        credits: 2,
        yearLevel: 2,
        semester: '前期',
        dayPeriod: '水曜2限',
        instructor: '小泉 恵',
        takenStatus: 'not_taken',
        matchState: 'eligible_for_this_category',
      }),
      createCourse(CATEGORY_IDS.free, {
        courseId: 'project_showcase',
        courseCode: 'FRE104',
        courseName: '学内プロジェクト展示',
        credits: 2,
        yearLevel: 4,
        semester: '後期',
        dayPeriod: '木曜4限',
        instructor: '森 由美',
        takenStatus: 'passed',
        matchState: 'counted_in_other_category',
        countedCategoryId: CATEGORY_IDS.requiredElective,
        countedCategoryName: '選択必修',
        eligibleCategoryIds: [CATEGORY_IDS.free, CATEGORY_IDS.requiredElective],
      }),
      createCourse(CATEGORY_IDS.free, {
        courseId: 'independent_study',
        courseCode: 'FRE105',
        courseName: '自主研究',
        credits: 2,
        yearLevel: 4,
        semester: '通年',
        dayPeriod: '金曜5限',
        instructor: '鈴木 花',
        takenStatus: 'not_taken',
        matchState: 'not_eligible',
      }),
    ],
  },
];

export const mockRequirementCategories = mockRequirementCategoryDetails.map(summarizeDetail);

export async function fetchRequirementCategories(): Promise<RequirementCategorySummary[]> {
  await delay(MOCK_DELAY_MS);
  return mockRequirementCategories.map((category) => ({ ...category }));
}

export async function fetchRequirementCategoryDetail(categoryId: string): Promise<RequirementCategoryDetail> {
  await delay(MOCK_DELAY_MS);

  const detail = mockRequirementCategoryDetails.find((category) => category.categoryId === categoryId);
  if (!detail) {
    throw new Error('区分詳細を取得できませんでした。');
  }

  return {
    ...detail,
    courses: detail.courses.map((course) => ({
      ...course,
      eligibleCategoryIds: [...(course.eligibleCategoryIds ?? [])],
    })),
  };
}
